# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='analysis.proto',
  package='analysis',
  syntax='proto3',
  serialized_options=b'Z\"github.com/hzget/analysis/analysis',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"\x16\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x06Status\x12\r\n\x05score\x18\x01 \x01(\x05\x32G\n\x0c\x44\x61taAnalysis\x12\x37\n\x0f\x41nalyzeByAuthor\x12\x10.analysis.Author\x1a\x10.analysis.Status\"\x00\x42$Z\"github.com/hzget/analysis/analysisb\x06proto3'
)




_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='analysis.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='analysis.Author.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=50,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='analysis.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='analysis.Status.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Author'] = _AUTHOR
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.Author)
  })
_sym_db.RegisterMessage(Author)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None

_DATAANALYSIS = _descriptor.ServiceDescriptor(
  name='DataAnalysis',
  full_name='analysis.DataAnalysis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=77,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyzeByAuthor',
    full_name='analysis.DataAnalysis.AnalyzeByAuthor',
    index=0,
    containing_service=None,
    input_type=_AUTHOR,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAANALYSIS)

DESCRIPTOR.services_by_name['DataAnalysis'] = _DATAANALYSIS

# @@protoc_insertion_point(module_scope)
