# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"\x16\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x06Status\x12\r\n\x05score\x18\x01 \x01(\x05\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\x03\"\x1c\n\nPostResult\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t2\xb7\x01\n\x0c\x44\x61taAnalysis\x12\x37\n\x0f\x41nalyzeByAuthor\x12\x10.analysis.Author\x1a\x10.analysis.Status\"\x00\x12\x37\n\x0f\x41nalyzeByPostId\x12\x0c.analysis.Id\x1a\x14.analysis.PostResult\"\x00\x12\x35\n\x0b\x41nalyzePost\x12\x0e.analysis.Text\x1a\x14.analysis.PostResult\"\x00\x42!Z\x1fgithub.com/hzget/analysisdriverb\x06proto3')



_AUTHOR = DESCRIPTOR.message_types_by_name['Author']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_ID = DESCRIPTOR.message_types_by_name['Id']
_POSTRESULT = DESCRIPTOR.message_types_by_name['PostResult']
_TEXT = DESCRIPTOR.message_types_by_name['Text']
Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.Author)
  })
_sym_db.RegisterMessage(Author)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.Status)
  })
_sym_db.RegisterMessage(Status)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.Id)
  })
_sym_db.RegisterMessage(Id)

PostResult = _reflection.GeneratedProtocolMessageType('PostResult', (_message.Message,), {
  'DESCRIPTOR' : _POSTRESULT,
  '__module__' : 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.PostResult)
  })
_sym_db.RegisterMessage(PostResult)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.Text)
  })
_sym_db.RegisterMessage(Text)

_DATAANALYSIS = DESCRIPTOR.services_by_name['DataAnalysis']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037github.com/hzget/analysisdriver'
  _AUTHOR._serialized_start=28
  _AUTHOR._serialized_end=50
  _STATUS._serialized_start=52
  _STATUS._serialized_end=75
  _ID._serialized_start=77
  _ID._serialized_end=93
  _POSTRESULT._serialized_start=95
  _POSTRESULT._serialized_end=123
  _TEXT._serialized_start=125
  _TEXT._serialized_end=145
  _DATAANALYSIS._serialized_start=148
  _DATAANALYSIS._serialized_end=331
# @@protoc_insertion_point(module_scope)
